services:
  homeassistant:
    container_name: homeassistant
    image: ${HOMEASSISTANT_IMAGE}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    ports:
      - "8123:8123"
    volumes:
      - ./homeassistant/config:/config
    networks:
      - smarthome

  esphome:
    container_name: esphome
    image: ${ESPHOME_IMAGE}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    ports:
      - "6052:6052"
    volumes:
      - ./esphome/config:/config
    networks:
      - smarthome

networks:
  smarthome:
    name: smarthome
