services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome:stable
    volumes:
      - ./esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
    restart: unless-stopped
    privileged: true
    network_mode: host

  cat-recognizer:
    container_name: cat-recognizer
    image: ${CAT_RECOGNIZER_IMAGE:-cat-recognizer:native}
    build:
      context: ./services/app-cat-recognizer
      dockerfile: src/main/docker/Dockerfile.native
    environment:
      CAT_RECOGNIZER_CAMERA_SNAPSHOT_URL: ${CAT_RECOGNIZER_CAMERA_SNAPSHOT_URL:-http://esp32-cam.local/snapshot}
      CAT_RECOGNIZER_DEBUG_MANUAL_TRIGGER_ENABLED: ${CAT_RECOGNIZER_DEBUG_MANUAL_TRIGGER_ENABLED:-true}
    restart: unless-stopped
    network_mode: host
