quarkus.package.jar.enabled=false
quarkus.native.enabled=true
quarkus.native.container-build=true
quarkus.container-image.build=true
quarkus.container-image.name=cat-recognizer
quarkus.container-image.tag=native
